language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"

install:
    - pip install -r dev-requirements.txt
    - pip install -e .

script:
    - py.test -v --pep8 caniuse/test/

notifications:
    email: false
